### ISSUE TITLE
How to let it know about Bootstrap CSS classes?

### ISSUE THREAD

**Issue by midiway** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#1]
If I am using Bootstrap via a remote CSS file, like https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css, how do I make your plugin find the CSS classes from it?

Is there some kind of configuration like:
```
{
    "css.remoteStyleSheets": [
        "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
    ]
}
```
?

**Comment by gencer** [comment]
@midiway please test new version.

Refer readme:
```
    "html-css-class-completion.remoteStyleSheets": [
		"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
	],
```
