### ISSUE TITLE
By default auto-completion doesn't work

### ISSUE THREAD

**Issue by exv3** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#10]
**OS** version `Windows 7`
**VSCode** version `1.31.0`
**Extension** version `1.2.1`

By default auto-completion doesn't work, besides:
- If I press `space` it does work and I can type my **second** class name which is okay
- If I press `ctrl` + `space` it does work but after pressing `space` and then `backspace` it doesn't anymore

![](https://i.imgur.com/zMkrvJY.gif)

**Comment by gencer** [comment]
I will fix this. Probably due to new regex matching pattern that I used in last version.
