### ISSUE TITLE
ID selectors are not detected

### ISSUE THREAD

**Issue by exv3** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#11]
**OS** version `Windows 7`
**VSCode** version `1.31.0`
**Extension** version `1.2.1`

CSS id selectors are not detected and can't be used (auto-completion)

![](https://i.imgur.com/gkGl0YK.gif)

**Comment by gencer** [comment]
Currently there is no `id` auto-completion availability in this extension. But I will look into this. Thanks for reporting.

**Comment by Kcko** [comment]
Sorry still not working: video (http://bit.ly/2UUz6dB) via hash nothing founded, via dot found both (but second is not a classname)
