### ISSUE TITLE
Optimalization

### ISSUE THREAD

**Issue by Kcko** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#14]
After add new class to HTML or CSS plugin run full scan of workspace => my cpu fun is whispering all day.
Pls look at on it and try to make some optimalization. 
No need run still new fullscan over the whole project (it should add to new selector or remove from existing cache , i think ...)

Thx!

**Comment by gencer** [comment]
Hey @Kcko, This happens when you "save" or unfocus a file, right?

If so, I will disable this feature. But you should know that, This extension is not new and primarily based on zignd's version. Their version does not have incremental changes feature. It will take time to implement such feature.

One thing came to my mind is **only scan current file** when you edit a file. This will make your CPU better and at low usage. However, this will take time too.

At the moment my only option is to disable this feature completely and you need to hit cache icon bottom of your VSCode manually to re-cache.

**Comment by Kcko** [comment]
Exactly, when i save file, plugin will rescan the project (My projects are huge a this behavior is very annoying).

> One thing came to my mind is **only scan current file** when you edit a file.
Yes, but this action should happen in the background automatically, what do u think?

**Comment by gencer** [comment]
I've made a fix for you and also published to marketplace. This will save CPU from going high. But you'll need to manually re-cache.

Find VSIX here: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.3.1

> Yes, but this action should happen in the background automatically, what do u think?

Yes, you're right. I will find a way to do this within extension.

I'm sorry that i do not gave you another option at the moment because I really need to look and think what should be implemented and how to properly rewamp cache. If you know JS, you can help me by sending a PR or you need to wait a little for this.

**Comment by gencer** [comment]
Okay. This is what we will do:

1. We will parse files but cache by using their paths.
2. Each file item will have its own selectors.
3. When file removed or added we will populate only those files
4. When a file changes (as you typed) we will only update that file.

This will work. I will change cache mechanism as soon as possible. I will remain this issue open and update here.

**Comment by Kcko** [comment]
Take a time :-), we are not in a hurry.
Ping me when it will be rady and i will test it completely. (I repeat, do not spit)

**Comment by gencer** [comment]
Here we go. First **beta** for `v1.4.0` : https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.4.0-beta

Now test this:

1. Install extension & Reload or restart vscode.
2. When cache init finishes, open a latte or html file and test if class completion works by typing one of your classes
3. Now create a class like class="anoter-class"
4. Save file. This time we will only index your changes. This wont consume your CPU.

Now you should be able to see your class in scss/css.

Report back to me.

**Comment by gencer** [comment]
P.S: There will be no delay like older versions. So, If you enable Auto save on focus in VSCode, you will get instant auto-completion across your files when you change/switch your tab.

**Comment by Kcko** [comment]
Hi,
really weird, adding new class = looking for classes in whole project :( percent progress is jumping between two strange values), cpu fan is spinning 

See video pls: http://bit.ly/2RUXdXY

**Comment by gencer** [comment]
Hm.. Could this be cached? I mean did you `uninstall -> restart -> install`. Let me look at this. I am working on locations (your other request) and also check this and send you another release.

But check one more time via uninstalling it and restarting. Sometimes extensions are not loaded in vscode. I faced similar issues before.

**Comment by Kcko** [comment]
uninstal -> restart -> install -> restart again.
Ok adding new class -> no scan -> well.

In scss i cannot find a newly added claseses. (Im pressing this icon ) 
![](http://bit.ly/2RUypz9) -> scan 
-> scan all classes in the workspace (still not good, it should scan only in the  file where i maked changes).

scss file 
all newly added class i find - well!

Good progress.

See my testing video: (id was not found, new classes was found, bud when is on last position, i cannot see full name etc ..., still fullscan)
http://bit.ly/2RROENu
This is expected behavior  for all previous point or am I doing something wrong?

**Comment by gencer** [comment]
> In scss i cannot find a newly added claseses. (Im pressing this icon )

I will try to reproduce and fix this.

> scan all classes in the workspace

The button is there for that. If you click button, it will scan whole workspace. For single file, you need to press `CTRL + S`. Basically, you need to save that file to get indexed.

> id was not found, new classes was found,

Yes there is no # support at the moment BUT I will also add that! ;)

I will make everything faster. But just a curiosity. You must be have a millions of file. :)

**Comment by Kcko** [comment]
> The button is there for that. If you click button, it will scan whole workspace. For single file, you need to press `CTRL + S`. Basically, you need to save that file to get indexed.

oops, ok, i didnt know. But this means that its not working as expected (video), ctr +s => no change in cache (i dont see new classes / id).

We (You) are close to great success! 
Thx for great work & fast reaction / cooperation.

**Comment by gencer** [comment]
Anytime. Thanks for reporting and using this extension. 

I am working on it. Will update here.

**Comment by gencer** [comment]
@Kcko please try this for single-file update.

v1.5.1-beta: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.1-beta

Note: This is still BETA. Need lot of work but it should be faster than before.

**Comment by gencer** [comment]
@Kcko I forgot to say. uninstall first. You may hit the cache again in vscode extensions.

**Comment by gencer** [comment]
Optimization made. Please reply here if you encounter high cpu usage when you save a single file.

**Comment by Kcko** [comment]
Optimalization looks sweet! New classes are added "asap". High cpu is not so high like an afternoon.
But i found a few bugs, i will create a new issue.
