### ISSUE TITLE
Small bugs after new release (1.5.3)

### ISSUE THREAD

**Issue by Kcko** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#15]
At first, speed is fantastic - happiness 👍 

I have discovered a few "bugs":  

### Bugs
1)  Searching in php files does not work (video: http://bit.ly/2UPeYcY)
2) There is no distinction between id and class (id searching does not work and searching via dot find both), you probably know it, but i dont know if it is in progress or its done and its a bug :-) 
3) Path to file where is located is missing when im looking for a class from another scss file (video: http://bit.ly/2UQETkz)
4) Im loading scss version of twitter bootstrap in version 3 in main.scss (its a core scss file of project), i never see classes from bootstrap :( (http://bit.ly/2UN2e6C) some classes  are probably found (but without path info, see previous point, and some classes are not found -  eg: ```.btn-primary``` - dont understand this behavior.

5) When is some class together with other and i want to put from suggestion list i get all of them (video: http://bit.ly/2UQFnXV) (this point has a low priority , maybe makes a sense - i dont know)

Thx mate.

**Comment by gencer** [comment]
> At first, speed is fantastic - happiness 👍
> 
> I have discovered a few "bugs":
> 
> ### Bugs
> 1. Searching in php files does not work (video: http://bit.ly/2UPeYcY)

Try this: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.4-beta

> 2. There is no distinction between id and class (id searching does not work and searching via dot find both), you probably know it, but i dont know if it is in progress or its done and its a bug :-)

I'm working on it. You will get this update soon. I am aware of this bug.

> 3. Path to file where is located is missing when im looking for a class from another scss file (video: http://bit.ly/2UQETkz)

Try this: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.4-beta

> 4. Im loading scss version of twitter bootstrap in version 3 in main.scss (its a core scss file of project), i never see classes from bootstrap :( (http://bit.ly/2UN2e6C) some classes  are probably found (but without path info, see previous point, and some classes are not found -  eg: `.btn-primary` - dont understand this behavior.

I will check this.

> 5. When is some class together with other and i want to put from suggestion list i get all of them (video: http://bit.ly/2UQFnXV) (this point has a low priority , maybe makes a sense - i dont know)

This will be fixed in next build.

Please check this build for PHP and SCSS: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.4-beta

**Comment by Kcko** [comment]
Can you help me how to install it? http://bit.ly/2RX6mz8
Replace old directory with new one (1.54.)?

**Comment by gencer** [comment]
No @Kcko, never do that!

Open VSCode, go to extensions, click three dots and click install from vsix. Restart.

![image](https://user-images.githubusercontent.com/1711576/52632584-06e29300-2ed3-11e9-9094-267474bb63ca.png)

**Comment by gencer** [comment]
Btw, after I add SCSS find uages feature, auto complete becomes very slow. Let me know if you see that slowness.

**Comment by Kcko** [comment]
Thx for instruction to vsix - i didnt know that.

1) Still not working http://bit.ly/2RTMmxj
2) OK, we skip for now
3) Works! http://bit.ly/2RW4bMr and (http://bit.ly/2RX4TsO - still works, great!) - but php files not, see point 1
4) ok - pending state, i will wait
5) ok - pending state, i will wait

**Comment by gencer** [comment]
Okay. I'M on it. I will do PHP at last. First I will fix css/scss completion for ids and classes separately.

**Comment by gencer** [comment]
![image](https://user-images.githubusercontent.com/1711576/52633861-b66d3480-2ed6-11e9-8772-9da74405059d.png)

This is how ID will look a like.

**Comment by Kcko** [comment]
Looks good!

**Comment by gencer** [comment]
Something is keeping me away to use `#` in scss. When I type `#` there is no autocomplete window. But I strictly define it.

Until I find a better way, you put `.` and can change to `#` after complete. You will see IDs like above.

**Comment by gencer** [comment]
Hey @Kcko, can you try this build for PHP and IDs?

Note: When you put `#`, you will NOT get auto completions. Just put `.` like you define class and search for `ID` and see if it comes up. This is known bug for `#` and i will find a solution later.

v1.5.5-beta: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.5-beta

**Comment by Kcko** [comment]
@gencer I tested it and seems to work it!
http://bit.ly/2X0nDer  (small improvement: ```poll-percent```` has 4 ocurrencies, and i see it twice , should be all together) :-)

**Comment by gencer** [comment]
Yes, I'm aware of it. Will fix in next build ;)

**Comment by Kcko** [comment]
@gencer Im happy, http://bit.ly/2WQJjcW  plugin can find buttons from bootstrap 👍

**Comment by Kcko** [comment]
http://bit.ly/2WYaUcf  it corresponds to reality - WELL

**Comment by gencer** [comment]
@Kcko I am very happy to hear that. Yes, I enabled that on previous commit.

> http://bit.ly/2WYaUcf it corresponds to reality - WELL

As long as işt shows you buttons, its not problem. I will fix this multiple fields don't worry!

My only question: Does buttons shows up or not?

I will fix rest.

**Comment by Kcko** [comment]
> Yes, I enabled that on previous commit.

Any exception for BS? I hope not.

> I will fix this multiple fields don't worry!

You have already finish many demands, this is nothing critical, no worries!

> My only question: Does buttons shows up or not?

Sorry, dont understand, what do you mean with "shows up"?

**Comment by gencer** [comment]
> Any exception for BS? I hope not.

No exceptions. All there.

> You have already finish many demands, this is nothing critical, no worries!

Thanks! And thank you for your patient and your visual videos!

> Sorry, dont understand, what do you mean with "shows up"?

I mean when you write `btn-p...` you see the completions. That's the matter.

**Comment by Kcko** [comment]
Yes i see completitions :-) 
You have to look at my videos from time to time :D

**Comment by gencer** [comment]
Yes, I watched all! I was just repeating that's all.

**Comment by Kcko** [comment]
Relax, just kidding ;)

**Comment by Kcko** [comment]
We can probably close this issue.
Can you create a "roadmap" with unresolved points? (readme.md is the right place)
Thx!

**Comment by gencer** [comment]
Hehe. No worries. In fact, watching videos helped me a lot to understand what is requested. Thank you one more time for uploading videos and your patient.

Here is a fixed version: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.6-beta

This has to fix your "multiple occcurrences" issue. Let me know if not.

**Comment by gencer** [comment]
Issue closed per request and fix.

**Comment by gencer** [comment]
@Kcko Sure I will prepare a roadmap (i have few things in my mind too) and put it to README.

**Comment by gencer** [comment]
I've reopened this issue due to ID starts with `#`. Wait a reply from me, I will also add this feature and release on marketplace.

**Comment by gencer** [comment]
Finally here.

Just IDs:

![image](https://user-images.githubusercontent.com/1711576/52640158-e290b180-2ee6-11e9-9030-9f5c948f3be6.png)

Just classes:

![image](https://user-images.githubusercontent.com/1711576/52640169-ea505600-2ee6-11e9-8ce9-01d2a8c4de90.png)

**Comment by Kcko** [comment]
Tiny bug http://bit.ly/2WZMVJY

**Comment by gencer** [comment]
Sorry for late reply. It was 17:00 (a Turkish coffee time in our house)

I will try to fix this. I found the problem. But first lets handle IDs.

**Comment by Kcko** [comment]
:-) im not your boss and ur plugin is free = no worries :-) organize your time for developing as you need.

**Comment by gencer** [comment]
Ah, I know that. But I also love being productive when I am coding. I need those features as much as you need.

**Comment by Kcko** [comment]
do not say twice, im very  demanding and iI can bring you to madness :-D

**Comment by gencer** [comment]
Here we go. Try this: Especially with ID and multiple issue and let me know.

Download: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.7

**Comment by Kcko** [comment]
Identicators are founded after opening new workspace and after init fullscan, later nope.

Classes works fine.

http://bit.ly/2RXC9jv

**Comment by gencer** [comment]
Fixed.

**Comment by gencer** [comment]
Here: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.9

**Comment by Kcko** [comment]
Sorry, not for me: http://bit.ly/2WQRjdY

**Comment by Kcko** [comment]
Oops, now its working (some fu**** delay).

**Comment by gencer** [comment]
Hm.. delay. It shouldn't. Can you re-test? If it slow again. I will look deeper

**Comment by Kcko** [comment]
Bug: when you have same name for class and for id probably: (behaves accidentally)
http://bit.ly/2WQRrds

**Comment by Kcko** [comment]
but I notice slower intelisense sometimes ...we have to focus on it (performance is number one)

**Comment by gencer** [comment]
Yes, Indeed. Now I'm closing this. I opened two different issues and will update there. You may subscribe them.

#17 and #16.

Thanks!
