### ISSUE TITLE
Peek definition and link to class style

### ISSUE THREAD

**Issue by imichall** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#18]
Hi, 

thanks for huge upgrade since yesterday. I'd like to ask you for some feature. Is it possible to make classes linkable to each scss style? I mean for example in latte:

where is for example span with class label

`<span class="label">{label phone}</span>`

and what would be great, make a class="label" linkable to style label.scss.

<img width="789" alt="snimek obrazovky 2019-02-13 v 12 03 09" src="https://user-images.githubusercontent.com/26431861/52707155-5c787780-2f87-11e9-996d-b23343eb5625.png">

**Comment by gencer** [comment]
Hi @imichall, 

You mean `ctrl + click`? (`Go to definition`?)

**Comment by imichall** [comment]
> Hi @imichall,
> 
> You mean `ctrl + click`? (`Go to definition`?)

Exactly :)

**Comment by gencer** [comment]
Yes, this is possible. My proposal would be;

- Check if class or id used in single file. If so, open that file directly.
- If more then one usage found, open a popup and let user to choose which one should be opened.

**Comment by gencer** [comment]
Furthermore, I will try to implement a basic support first on my end and update here.

**Comment by Kcko** [comment]
@imichall , @gencer 
You talk about click & jump to file which i selected (clicked) from popup window with occurences?
http://bit.ly/2RWFrDv

**Comment by gencer** [comment]
No. Let say you write a latte template and there is a class in it. When you `ctrl + clik` on that element it will open related SCSS/CSS file.

**Comment by Kcko** [comment]
@gencer oh, now i understand.
Its that basically same action like as in my prev video, or not?

**Comment by imichall** [comment]
@gencer yes, that's what I mean :) And yes, I've tried it and the class is in single file. When I try to  use cmd (macos) and hover on .some-class. Then it shows me, where is the class used. But I need, as you said, link from latte, html, php into definition directly to scss :)

**Comment by gencer** [comment]
I will look how vscode handle such actions and try to implement.

**Comment by Kcko** [comment]
@gencer You will have a lot of work because VSC is little buggy with this behavior, see my issue on VSC channel: https://github.com/Microsoft/vscode/issues/66984

**Comment by imichall** [comment]
Hi, how are you? Do you remember to my question of link from html, latte to each class style into defined style in scss? Have you already check it or started on it, please?

**Comment by gencer** [comment]
Hi @imichall, Yes, I will work on that. I am another city and will return to home in a a week. This is why i did not go forward with any issues yet.

But, what I learned is that it requires some kind of language server/client. I also get some high cpu alerts from users. I hoped to fixed them before, Still weird.

**Comment by imichall** [comment]
Hi, how does it look? Just asking. Thanks for reply.

**Comment by gencer** [comment]
It seems we need language server for this. I was hoping to implement without it byt that is the way how it should be handled which is require significant changes that i cannot have at the moment. But this is on my radar so subscribe on this thread.

**Comment by gencer** [comment]
**Update:** I might be a found a way of doing this without Language Server/Client via `Hover` feature.

I will try to implement this.

/cc @imichall
