### ISSUE TITLE
css

### ISSUE THREAD

**Issue by YHF7** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#2]
Failed to cache the CSS classes in the workspace for the first time: Failed to cache the class definitions during the iterations over the documents that were found: Failed to parse the documents: Cannot read property 'call' of undefined

**Comment by gencer** [comment]
Hey @YHF7,

I need more information about this.

1. Is it a fresh install without any modification to configs?
2. OS, VSCode versions.
3. Do you also use other SCSS extension at the same time? (from zignd)

Also any console debug info would be awesome if you have.

**Comment by gencer** [comment]
好的。 祝你有美好的一天！
