### ISSUE TITLE
The extension isn't working at all

### ISSUE THREAD

**Issue by horlorlahdeh** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#22]
Issue Type: <b>Bug</b>

The lighening Image isn't showing to indicate that the extention is active. I have uninstalled and installed severally but still not working.

Extension version: 1.5.12
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz (4 x 2167)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.90GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by gencer** [comment]
I've tested on fresh installed Windows. However, I cannot reproduce this behavior...
