### ISSUE TITLE
Not working for .Slim files

### ISSUE THREAD

**Issue by pmunin** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#27]
Does highlight or give any intellisense for a slim files. Slim files are treated as plaintext

**Comment by gencer** [comment]
Have you installed this extension: https://marketplace.visualstudio.com/items?itemName=sianglim.slim

**Comment by pmunin** [comment]
Is this step mentioned in its instructions somewhere?
I only installed https://marketplace.visualstudio.com/items?itemName=gencer.html-slim-scss-css-class-completion.  and reading "Supported Language Modes" : "Slim" makes me think that it will make autocomplete and highlight work for slim files.

**Comment by gencer** [comment]
Sorry for misleading. This extension will not work without that extension.

I will clearly state this in README.

**Comment by gencer** [comment]
I've go ahead and added requires note to the slim.

Closing this issue favor on this change.
