### ISSUE TITLE
html.erb issue?

### ISSUE THREAD

**Issue by sndrs** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#29]
I have a workspace setting for `"html-css-class-completion.includeGlobPattern": "dist/framework.css"`. that file definitely exists, and the extension seems happy it's indexed everything

<img width="524" alt="image" src="https://user-images.githubusercontent.com/867233/55477101-39c22100-5610-11e9-95b3-f2ea83ebc16e.png">

but no classes ever come up in `html.erb` files... 

![Kapture 2019-04-03 at 12 46 18](https://user-images.githubusercontent.com/867233/55476471-90c6f680-560e-11e9-8045-3a1b0bde3165.gif)

I'm sure I'm doing something stupid but I can't think what! any ideas? would you expect this to work?

**Comment by gencer** [comment]
Hey Alex, I couldn't reproduce this issue. Can you just use this:

```
"html-css-class-completion.includeGlobPattern": "**/*.{css,scss,sass,slim,latte,html,twig,php,erb}",
```

With above config, is it working?

![image](https://user-images.githubusercontent.com/1711576/55489244-38a5e980-563a-11e9-97f5-39b423672182.png)

Above sample used this config:

```
"html-css-class-completion.includeGlobPattern": "dist/bootstrap.min.css",
```

Could you send me the `erb`, `css` and `settings.json` file?

If you want send them to `gencer@nienbo.co.uk` so they stay hidden here.

**Comment by gencer** [comment]
BTW, which **extension** do you use for highlighting `erb` files?

**Comment by sndrs** [comment]
hi gencer, thanks for having a look!

I've just done as you did, put together a very simple project with one `erb` file and the exact same css file I'm hoping to load:

```json
{
    "html-css-class-completion.includeGlobPattern": "dist/styles.css"
}
```
<img width="222" alt="image" src="https://user-images.githubusercontent.com/867233/55495003-dd70f880-5633-11e9-8383-370ecceb7f65.png">

everything worked as you'd expect.

however, comparing the output in dev tools, the simple project reported:
```
[Extension Host]% 1 parseable documents found
console.ts:134 [Extension Host]% 1846 CSS class definitions found
console.ts:134 [Extension Host]% 857 unique CSS class definitions found
console.ts:134 [Extension Host]% 0 failed attempts to parse. List of the documents:
```
while the original one that's not working reports
```
[Extension Host]% 1 parseable documents found
console.ts:134 [Extension Host]% 35087 CSS class definitions found
console.ts:134 [Extension Host]% 6853 unique CSS class definitions found
console.ts:134 [Extension Host]% 0 failed attempts to parse. List of the documents:
```

they're both only trying to index one file, and the file is the same both times.

**Comment by sndrs** [comment]
> BTW, which extension do you use for highlighting erb files?

just the `rebornix.ruby` one :) theme is monokai pro

**Comment by gencer** [comment]
This is weird. It should result the same numbers on both cases if the files are exact same. I will investigate this difference on my end.

BTW, When you use `default settings` on your existing project (_not the test one_), does it work? Or, Only works on empty project just like above?

**Comment by sndrs** [comment]
default settings made no difference unfortunately. i think I first focused the globbing on to that single file because it's a big project, a lot of sass partials around and a lot of css files in dist I don't need to know about. I wonder if that makes a difference? feels as though the glob is returning extra things maybe?

it wouldn't explain what the weird thing about the main project is though... is there a way to enable more thorough debugging by any chance?

**Comment by gencer** [comment]
Sorry for late reply. I had a surgery. Anyway, do you see the file (css one) after this console logline:

![image](https://user-images.githubusercontent.com/1711576/55670732-b105e800-5890-11e9-977a-9ae5ef9ea84f.png)

I will try to add more verbose logging to the extension.

**Comment by sndrs** [comment]
hi @gencer – sorry for not getting back to you, but I've just noticed it's started working as expected! I've no idea what's changed, but it has :)

**Comment by gencer** [comment]
hi @sndrs, I am very happy to hear that! Let me know if you encounter any other issues.
