### ISSUE TITLE
[Feature Request] Code assistance in CSS/SCSS files

### ISSUE THREAD

**Issue by syedsameerali** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#3]
Dear Gencer, thank you for the excellent work with the html-slim-scss-css-class-completion extension. I was hoping if you could please offer some insight regarding the support for code completion in CSS/SCSS files for class attributes defined in HTML files. 

Currently the extension only scans the work-space for class style definitions within CSS/SCSS files.

It does not scan the work-space for class attributes within HTML files. As such, while editing and creating CSS/SCSS files there are no code suggestions offered.

I can see how currently, the code suggestions are helpful in the case of CSS frameworks (such as Bootstrap etc.), when the style-sheets already exist, and one wishes to simply add the available classes to the class attributes in the HTML markup.

It is my understanding, the structure of the HTML document is created first, and only afterwards, are the styles created for the relevant class attributes that exist in the HTML markup. As such, scanning the HTML documents would be very helpful, to allow class name suggestions for use while editing and creating the style-sheets.

 I find this to be a severely overlooked feature in Vscode, although it is a common feature which is found in several widely used IDE's such as Netbeans and those by Jetbrains. I was hoping this might be taken into consideration as a feature request since i'm sure many others look forward to this as well.

Thanking you, and best regards

**Comment by gencer** [comment]
Let me try few steps from my end and we can discuss further. But as far as I understand, When you write html attributes like this:

`<div class="my-class">...</div>
`
You expect from CSS/SCSS files to autocomplete like this:

**test.scss**:
`.my # < auto completes my-class`

Thank you,
Gencer.

**Comment by gencer** [comment]
I think we can do that! Actually, for slim language, I needed this feature, too!

How we going to handle cache? This is another question. I think I can add cache refresh every x minutes or seconds depending user value in settings.

**Comment by syedsameerali** [comment]
This is great news, Thank you ever so much for your help.

> <div class="my-class">...</div> 
> You expect from CSS/SCSS files to autocomplete like this:
> .test.scss:
> .my # < auto completes my-class

I'm afraid I may not have understood correctly but I have included a video screen capture below with an attempt to describe how the functionality works in other IDE's. In this example a comparison with the Net-beans IDE. (Thumbnail Below is a YouTube link) @Time: 1:25 Netbeans CSS/SCSS Code assistance Feature.
 
[![Youtube Video Feature Request](https://img.youtube.com/vi/anxg7HnsxMY/maxresdefault.jpg)](https://youtu.be/anxg7HnsxMY)

As for caching, most likely I do not have the experience to suggest anything pertinent, but I look forward to helping out in any way that I could.

**Comment by gencer** [comment]
Yup. We're on the same page. This is exactly what I referred. I will try few cache / live models and update here.

**Comment by syedsameerali** [comment]
Just out of curiosity, wouldn't it be ideal for the cache to update dynamically on file change or text change, to provide real time coding assistance, without the need for manual intervention or a time interval to update the cache. Or is this something that is not feasible performance wise?

**Comment by gencer** [comment]
> Just out of curiosity, wouldn't it be ideal for the cache to update dynamically on file change or text change, to provide real time coding assistance, without the need for manual intervention or a time interval to update the cache.

There could be hundreds of CSS/SCSS files in one workspace. Triggering cache warm on each file save/focus, we spend too much time to build whole workspace.

I think 2 options here.

1. We only do this cache update dynamically for HTML files. So, you will get almost instant updates when typing classes from html to scss (thats what you want)
2. We can add crazy option and give user a choice for that. If user believes that cache will be fast and less work, than user can choose between dynamic update and manual update.

For example, I would do dynamic update on my PC because currently even largest project of mine takes 2 seconds to cache all SCSS/CSS files.

**Comment by gencer** [comment]
@syedsameerali, this feature is in `master` branch. I will release a new version when I complete.

**Comment by gencer** [comment]
Released in `v1.2.0`
