### ISSUE TITLE
Scan for CSS classes in workplace freezes at 99.xx%

### ISSUE THREAD

**Issue by shiftgeist** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#31]
Reported this here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/154

This is still happening
![image](https://user-images.githubusercontent.com/30648730/57697921-9cb5c780-7654-11e9-9946-dfbac0880364.png)

Idea: Maybe this is a caching problem because some are still available?
![image](https://user-images.githubusercontent.com/30648730/57698018-d5ee3780-7654-11e9-91c6-c012e7ef0024.png)

Idea 2: Could it help to ignore `node_modules`?

Log when it froze:
```
console.ts:134 [Extension Host] Looking for parseable documents...
console.ts:134 [Extension Host] Found all parseable documents.
console.ts:134 [Extension Host] Parsing documents and looking for CSS class definitions...
```

After window reload (solves it 50% of time):
```
console.ts:134 [Extension Host] Looking for parseable documents...
console.ts:134 [Extension Host] Found all parseable documents.
console.ts:134 [Extension Host] Parsing documents and looking for CSS class definitions...
console.ts:134 [Extension Host] Summary:
console.ts:134 [Extension Host]% 2641 parseable documents found
console.ts:134 [Extension Host]% 179736 CSS class definitions found
console.ts:134 [Extension Host]% 4538 unique CSS class definitions found
console.ts:134 [Extension Host]% 3 failed attempts to parse. List of the documents:
console.ts:134 [Extension Host]
project/app/node_modules/angular-ui-bootstrap/src/tooltip/docs/demo.html
project/app/bower_components/angulartics/samples/inspectlet.html
project/app/node_modules/angulartics/samples/inspectlet.html
```

Its more stable than the old plugin but not rocket super duper stable :smile: 

## More info:

HTML-CSS-Class-Completion still installed? Nope, but switched

Project has 100+ SCSS files

**Comment by gencer** [comment]
I reproduced this behavior on one of my workspaces, which is very large. I will try to implement a workaround. But i have to make sure this is not related to VSCode `1.31.1`.

**Comment by shiftgeist** [comment]
I'm currently working on vscode 1.33.1

**Comment by gencer** [comment]
Did this also happens on previous VSCode versions or only introduced in 1.33.1?

**Comment by shiftgeist** [comment]
Yes this also happend on previous version.

**Comment by gencer** [comment]
Do you set `"html-css-class-completion.excludeGlobPattern"` to `""` in your settings.json?

In my large project,  I set this option to blank. This causes stuck at 99%. This mean it process `node_modules/`. When I remove that key (which is default point to node modules) it worked.

**Comment by gencer** [comment]
I have added node settings to exclude note strictly. I will test and publish soon.

**Comment by gencer** [comment]
I've changed CSS/SCSS Pre-processor usage. Can you try with latest version? Also `node_modules` is in exclude path.

**Comment by shiftgeist** [comment]
Great to hear! I've tested it a few hours (version 1.5.17) and I think it's gotten better, but it's still gets stuck a some times. I'd say it works 60% of the time.

**Comment by shiftgeist** [comment]
I had another idea: How about ignoring all .gitignore(ed) files? When you build a project folders like public, dist or temp beeing generated with css files inside, but they are only a compiled version of the classes that exist in the source and this could save some time.

I don't know if you could make it work with `.gitignore` paths because of the `!keep/folder/`, `example.file` and `node_modules/` symantic and also the relative paths. But how about an array of paths in the `vscode/settings.json` that you can define globally and per project?

**Comment by gencer** [comment]
We may support `.gitignore` as a secondary source of exclude setting. First we look for include and exclude via `settings.json` then add more ignores based on `.gitignore`.

BTW, have you ever tried `excludeGlobPattern` setting that mentioned in `README`?

**Comment by shiftgeist** [comment]
I didn't know there where so many usefull settings for your plugin. It works by removing .css files from `include glob pattern`.

:+1: Thank you for your awesome maintenance of this plugin. :tada:

**Comment by gencer** [comment]
I'm very happy to hear that. 🎉 Thanks! If you encounter any issue, do not hesitate to open a new issue.
