### ISSUE TITLE
Double period insert in a `.slim` file

### ISSUE THREAD

**Issue by issei126** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#35]
OS: macOS 10.14.5
VSCode: 1.34.0
Extension: 1.5.14

When I choice suggestion, Double period insert.
I want to insert only one period.
![dupulicate_period](https://user-images.githubusercontent.com/2083116/58868149-b481e800-86f6-11e9-8c66-2e1d6f4179e1.gif)

Intellisense in class cause, it work fine.
![class](https://user-images.githubusercontent.com/2083116/58868234-e004d280-86f6-11e9-80e6-20a8f05b67c6.gif)

Can I fix this by some setting ?

I'm sorry poor English.
Thanks.

**Comment by gencer** [comment]
Fix is in the `master` branch. Will publish when I completely solve #33.

**Comment by gencer** [comment]
Please try this build:
[html-slim-scss-css-class-completion-1.5.15.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/3257975/html-slim-scss-css-class-completion-1.5.15.zip)


You can install this on extension panel.

**Comment by issei126** [comment]
@gencer 

> Please try this build:
> html-slim-scss-css-class-completion-1.5.15.zip

It work fine ! Thanks !
