### ISSUE TITLE
Failed to cache error popup

### ISSUE THREAD

**Issue by Steve30** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#38]
Failed to cache the CSS classes in the workspace for the first time: Failed to cache the class definitions during the iterations over the documents that were found: Failed to parse the documents: selectors[className].indexOf is not a function

**Comment by ksweetie** [comment]
This happens to me, too, every time I try to run the extension.

<img width="561" alt="Screen Shot 2019-07-09 at 8 49 22 AM" src="https://user-images.githubusercontent.com/2036284/60898743-89734280-a226-11e9-8d06-21daca58370e.png">

Let me know how I can give you more info if possible.

**Comment by gencer** [comment]
* Whats size of your workspace? A big one or small?
* Do you include `node_modules/`? If yes, Try to exclude it via config.
* Do you have a big-fat-single scss or css file? If so how many lines have it.

I also need a backtrace. You can open Developer Menu via `Help -> Toggle Developer Tools`

**Comment by ksweetie** [comment]
I set `"html-css-class-completion.includeGlobPattern"` to be more restrictive and that did the trick. It must've been picking up `node_modules` or something else. Thanks for your quick help!

**Comment by gencer** [comment]
Glad it did worked! Let me know if you need anything else.

**Comment by gencer** [comment]
Fixed in `1.5.18`.
