### ISSUE TITLE
In .vue file, CSS class intellisense may need a leading space to start

### ISSUE THREAD

**Issue by YipingRuan** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#4]
I am not sure if it is only me. If the class is cleared, I need to input a leading space. Only happens in .vue file.

![css](https://user-images.githubusercontent.com/5492274/48045136-02b72300-e1ca-11e8-8684-e1d7703403b9.gif)

**Comment by gencer** [comment]
Fixed in `master`
