### ISSUE TITLE
Inconsistent versions

### ISSUE THREAD

**Issue by Alex-Dinu** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#44]
Hi, is it possible to update github version to reflect the one in the market place? My company needs to approve the software, but they can't since the versions are out of sync.

Thanks
Alex

**Comment by gencer** [comment]
You mean: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.20

Gencer.

**Comment by gencer** [comment]
Closing as for both due to inactivity and favor of released tag.
