### ISSUE TITLE
It doesn't work with .html.erb files

### ISSUE THREAD

**Issue by ricardoruwer** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#45]
I couldn't make it work in `.html.erb` files!

When I'm editing a pure HTML file:
![](https://media.giphy.com/media/VHZeordRb0ej55g1uK/giphy.gif)

But when I change to `.html.erb`:
![](https://media.giphy.com/media/RkVzCtuWagT8tRKWcn/giphy.gif)

I'm currently using the Ruby extension https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

**Comment by gencer** [comment]
Hi @ricardoruwer i think i might found the issue.

To make sure i found the right issue source, can you install this and try?

https://marketplace.visualstudio.com/items?itemName=CraigMaslowski.erb

After installing this, if it works we will handle this in the future.

**Comment by ricardoruwer** [comment]
Thank you for the quick answer ❤️ 
I installed this new extension, and:

The Emmet doesn't work:
e.g. when I type `h1` and press TAB it doesn't create the `<h1></h1>`.

But the IntelliSense works :)
e.g. when I type `<h1 class=""></h1>` the HTML classes appear in the list...

**Comment by ricardoruwer** [comment]
Actually, I'm not sure... 🤔 
Forget what I said...

I think this extension you said makes no difference...
When I change the language mode (`CMD+K M`) and type `erb` I have 2 options on the list:
- html.erb
- erb

In this `html.erb` nothing works (emmet and any other autocomplete)
(I don't know if the emmet operation is a responsibility of this extension)

And in this `erb` just the class completion works;
e.g. when I type `<h1 cla` there is one `class` on the list, and when I select it, it completes just with `class` but I think it might complete with `class=""`, you know?
And when I type e.g. `<h1 class="` the class completion works

But apparently this extension you said https://marketplace.visualstudio.com/items?itemName=CraigMaslowski.erb makes no difference to this

**Comment by gencer** [comment]
Hmm.. Strange. Let me evaluate on a fresh installation.

**Comment by ricardoruwer** [comment]
It'll be nice to add support for Elixir (`.html.eex`) files as well 😄

**Comment by gencer** [comment]
`.eex` extension added.

**Comment by gencer** [comment]
`.eex` support has been released on marketplace. You may need an another extension to trigger language specific things.

**Comment by clementoriol** [comment]
Thanks for the eex support ! However, the language name seems incorrect, so it doesn't work.

The 2 major language extensions for Elixir uses different language names :
- ([vscode-elixir](https://marketplace.visualstudio.com/items?itemName=mjmcloug.vscode-elixir) uses `HTML (Eex)`
- ([elixirLS](https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls) uses `HTML (EEx)`

Could you please add `HTML (Eex)` and `HTML (EEx)` support ? That would made this plugin the first to support this feature for elixir afaik, since all the other ones seems inactive.

Thanks !

**Comment by gencer** [comment]
I didn't know that one exists. Yes, As soon as i back to home, i will add this support.

P.S.: You will need those extension as well to work with this extension. They are dependent.

**Comment by clementoriol** [comment]
Amazing, thank you for responding so quickly ! 👍 💯

**Comment by gencer** [comment]
BTW, a quick question while im on remote:

It is `HTML E(E|e)x`, right? Not `EEx` and `Eex`. It has `HTML ` at start.

**Comment by clementoriol** [comment]
Yes ! 

Here are the exact names for both cases :
 `HTML (Eex)`
`HTML (EEx)` 
They both contains `HTML ` and parenthesis.

**Comment by gencer** [comment]
Okay. I will prepare a custom build as soon as possible.

Please also note that, This will also includes #49 and #50. #49 is about fetching remote stylesheet from meta links in HTML compatible files instead of permanent setting in vscode.

**Comment by gencer** [comment]
# v1.7.0

@clementoriol, Please can you try this version:

[html-slim-scss-css-class-completion-1.7.0.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4511998/html-slim-scss-css-class-completion-1.7.0.zip)

**Comment by clementoriol** [comment]
@gencer Ok, so I had time to test this ! 
Tested both with `vscode-elixir` and `ElixirLs` extensions. 

- ✅ works great with `vscode-elixir` (lang set to `HTML (Eex)`)
- ❌ doesn't work with `ElixirLS` (lang set to `HTML (EEx)`) 

Did you had the chance to add both languages ? I know the case difference is a bit annoying, but sadly the libraries haven't done anything yet to harmonize it, afaik

**Comment by gencer** [comment]
Interesting. See, I already added EEx and Eex (lowercase and uppercase). I will try to find out why it didn't worked.

**Comment by clementoriol** [comment]
Nevermind, it actually works, I guess it just took some time to index the scss :) 
So, looks good to me, thank you 🎉🎉🎉

**Comment by gencer** [comment]
Ahh :=) No worries! If your project is big, it might take some time to warm up on first time. Later, it will incrementally build and re-cache.

Changes are on `master`. I will publish on marketplace v1.7.0 soon.

**Comment by gencer** [comment]
@clementoriol I found the issue. Fixed in master will be published in few minutes on marketplace. Please test v1.7.1 for EEx (uppercase E)
