### ISSUE TITLE
css class autocomplete

### ISSUE THREAD

**Issue by Highter87** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#47]
Hello!
Don't work css class autocomplete for *.svelte files.

![image](https://user-images.githubusercontent.com/17083227/67459300-e6153480-f640-11e9-9ac3-e1262db64b28.png)

**Comment by gencer** [comment]
`svelte`? Never heard of it. Interesting.

You can see supported types on **README.md**. We need to explicitly add this support.

**Comment by Highter87** [comment]
It is new javascript framework ) You can see: https://svelte.dev/
in short - this is an analogue of Vue.js cli

**Comment by gencer** [comment]
Hmm.. Looks interesting.

Well, lets add it!

I will try on my end and then prepare a VSIX file for you to test on your end. After validation, I will publish on marketplace.

**Comment by Highter87** [comment]
ok

**Comment by Highter87** [comment]
Hi, how are you?

**Comment by Highter87** [comment]
Hello gencer!
14 days have already passed since the discussion. I am still waiting for this task to complete.

**Comment by gencer** [comment]
Hi. I had health issues for a while. Were only able to respond few simple repos/issues or PRs and i only use PC for a while in a day.

I will look into this on this weekend. Please be hold.

Thank you for your patient.

**Comment by Highter87** [comment]
Ok. Get well

**Comment by gencer** [comment]
Please test this version and report back.

[html-slim-scss-css-class-completion-1.5.22.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/3832452/html-slim-scss-css-class-completion-1.5.22.zip)

**Comment by Highter87** [comment]
Fine! thank you friend
Everything works great. I will test before the end of this week, if I unsubscribe to this ticket

**Comment by Highter87** [comment]
Found a mistake
The value is defined as the name of the class.

![image](https://user-images.githubusercontent.com/17083227/68657204-4f071280-0544-11ea-8a31-0b65841d2f91.png)

**Comment by gencer** [comment]
Gotcha!

Thank you for this. I will fix it as soon as possible. Root case of this issue is from REGEX pattern. I will minimize findings.

**Comment by gencer** [comment]
Here you go. Please install (same version) again and test. I'll wait for your response.

[html-slim-scss-css-class-completion-1.5.22.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/3836834/html-slim-scss-css-class-completion-1.5.22.zip)
