### ISSUE TITLE
Smarty support

### ISSUE THREAD

**Issue by SharakPL** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#50]
Please add support for Smarty files.

Required extension e.g. [Smarty Template Support](https://marketplace.visualstudio.com/items?itemName=aswinkumar863.smarty-template-support), 
Language name: `"smarty"`
File extension: `.tpl`

**Comment by gencer** [comment]
Ah, Smarty! My old friend. Was using in old days with PHP.

I will add this to supported frameworks as soon as possible.

**Comment by SharakPL** [comment]
I know 😅 Unfortunately I'm forced to work with smarty. I've already made this extension work in .tpl by editing extension.js and adding ".tpl" and "smarty" to the lists with other languages, but it throws some errors in the console.

**Comment by gencer** [comment]
Why did you removed your comment. I was going to reply that :)

Anyway, Here you go please try and report back.

We will go through this.

[html-slim-scss-css-class-completion-1.6.1.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4480692/html-slim-scss-css-class-completion-1.6.1.zip)

**Comment by SharakPL** [comment]
Thanks :)
Unfortunately I can't test smarty support. There's a bug right at the start. Extension can't scan the workspace. There seems to be a problem with handling urls in the code. Didn't happen with previous version.
![obraz](https://user-images.githubusercontent.com/5007456/79435117-8f752b80-7fcf-11ea-8081-20c9303729fc.png)

Maybe it requires `http(s):`. Should it scan online resources by default?

![obraz](https://user-images.githubusercontent.com/5007456/79437458-8174da00-7fd2-11ea-89ef-b611c0c664b2.png)

**Comment by gencer** [comment]
Well, This is because of a new feature from #49. In the past remote urls have to be given by config file, after #49, HTML is being parsed and remotes automatically downloaded.

Let's add guard check for those URLs. Give it a try: 

[html-slim-scss-css-class-completion-1.6.1.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4486182/html-slim-scss-css-class-completion-1.6.1.zip)

**Comment by SharakPL** [comment]
I don't think it's a good idea. Most of the time it will create a lot of useless traffic and waste resources to scan online files that aren't even needed. Any online resource should be scaned **only** if explicitly requested by the config. This one should be default:

`"html-css-class-completion.searchRemoteGlobPattern": "",`

**Comment by SharakPL** [comment]
It seems to work fine now :)

**Comment by gencer** [comment]
@SharakPL , You're right! 

I made `searchRemoteGlobPattern` empty by default as you suggested. I will push to `master`. Do you want a pre-build for this change?

**Comment by SharakPL** [comment]
Thank you very much :)

**Comment by gencer** [comment]
I go ahead and close this issue due to resolved. Let me know if something doesn't work.
