### ISSUE TITLE
Extension autocompletes weird "class" strings in html, js and css

### ISSUE THREAD

**Issue by KasiMaru** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#6]
Extension Version: `1.2.0`
OS Version: `MacOS Mojave x64 v10.14.2`
VSCode version: `1.30.2`

First of all thanks for the awesome extension, it is (was?) a must have for me. Unfortunately, I can't use it now because it's keep autosuggesting me some weird classes and even ugly js expressions from out of nowhere. 

Tried with all extensions disabled, manually recaching, in html/css/jsx files — issue persists. Disabling the plugin obviously removes the issue.

Here's how it looks like:

![screencast 2019-01-09 09-58-59](https://user-images.githubusercontent.com/26373955/50882561-3561df80-13f6-11e9-9a8a-321ebfbeab0b.gif)

**Comment by gencer** [comment]
Confirmed.

I'm on it. I will provide a fix as soon as possible.

**Comment by gencer** [comment]
@KasiMaru, can you please test this version before I publish on marketplace?

**Note**: I've zipped `vsix` file due to restriction on GitHub.

[html-slim-scss-css-class-completion-1.2.1.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/2740060/html-slim-scss-css-class-completion-1.2.1.zip)

**Comment by gencer** [comment]
I've found one more issue. Let me fix that before.

**Comment by KasiMaru** [comment]
@gencer, Works like a charm! Tested both in `.jsx`, `.css` and `.html` file extensions, autocomplete suggestions are exactly what they should be. 

Thanks!

**Comment by gencer** [comment]
I'm happy to hear that. I will publish the new version now.

Thank you for reporting this issue.

Let me know if you encounter any issues.
