### ISSUE TITLE
Extension causes NG commands to take an extremely long time to run

### ISSUE THREAD

**Issue by StuartMc77** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#7]
I created a new angular 7 CLI application.  All was well, it compiled and ran when I used the` "ng serve" `command from either VS Code's terminal or a Command prompt.

Once the extension was installed (and enabled) running ANY ng commands, i.e. `"ng --version", "ng serve"` etc takes about 10 minutes to complete.

To replicate create a new Angular app using the command line application, run `"ng serve"` to compile and run the application before enabling the extension, all should work fine.  Enable the extension and run `"ng --version"` or any other ng command and it will take a very long time to execute.

**Comment by gencer** [comment]
Very interesting. Let me try on my end. At the moment i have no idea.
