### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Nuzairb** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#8]
- Issue Type: `Performance`
- Extension Name: `html-slim-scss-css-class-completion`
- Extension Version: `1.2.1`
- OS Version: `Linux x64 4.18.0-13-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/nuzair/gencer.html-slim-scss-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by gencer** [comment]
@Nuzairb, can you kindly help me on this?

1. Do you get this high cpu when you work on HTML/Slim files or all the time from extension loaded?
2. How many html files have you in your workspace? (any closer number will be ok)
3. Is your workspace small or huge?
